-- P1-S01-T06 durable idempotency lookup by key alone.
--
-- The workflow's start_session/1 retry must find the original commit by
-- idempotency_key without knowing the original session_id, since the
-- retry generates a fresh session_id. The existing
-- UNIQUE (session_id, idempotency_key) constraint requires the session_id
-- to be known at lookup time, so we add a global UNIQUE INDEX on
-- idempotency_key. Idempotency keys are random 16-byte opaque identifiers,
-- so global uniqueness is the right contract.
--
-- The per-session UNIQUE constraint from migration 0001 is left in place
-- because it is logically implied by the new global uniqueness and dropping
-- it would require recreating the table. The new index is the only one
-- that enforces the lookup contract.
--
-- Upgrade policy from v1:
--
-- A v1 store that stored two action_commits rows with the same
-- idempotency_key under different session_ids (the v1 constraint
-- permitted this) will fail to apply this migration. The migration is
-- applied inside one transaction; any duplicate row raises a SQLite
-- UNIQUE constraint failure and the runner rolls the entire batch back.
-- The store records no version increment and the operator is expected to
-- inspect the existing rows, deduplicate them by the stored request_digest
-- (the original idempotency contract was content-addressed, so a same-key
-- duplicate with a different stored digest is a real corruption), and
-- retry the migration. After applying this migration, the
-- action_commits_idempotency_key_idx is enforced and a v1 row with
-- per-session duplicates becomes a single global key per idempotency_key.
--
-- A v1 store that used the per-session constraint correctly (every
-- idempotency_key appeared once across the table) applies this migration
-- in one transaction and proceeds.
--
-- Tests in test/kiln/store/migrations_test.exs cover both paths.

CREATE UNIQUE INDEX action_commits_idempotency_key_idx
  ON action_commits (idempotency_key);
