#!/usr/bin/env python3
"""Deterministic integrity and catalog check for Project Arsenal."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "arsenal" / "registry.json"
CATALOG = ROOT / "CATALOG.md"
CANONICAL_GENERATOR = "prompt_design/master-sol-fable-super-prompt-generator.md"

KINDS = {"prompt", "prompt-package", "generator", "brief", "workflow", "template", "doctrine"}
STATUSES = {"source", "draft", "unverified", "testing", "stable", "deprecated"}
REQUIRED = {"id", "path", "category", "kind", "status", "purpose"}


def load_registry():
    with REGISTRY.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if data.get("schema_version") != "1.0.0":
        raise ValueError(f"unsupported schema_version: {data.get('schema_version')!r}")
    if not isinstance(data.get("assets"), list):
        raise ValueError("registry.assets must be a list")
    return data


def render_catalog(data):
    live = [a for a in data["assets"] if a["kind"] != "brief"]
    groups = {}
    for asset in live:
        groups.setdefault(asset["category"], []).append(asset)

    lines = [
        "# Project Arsenal Catalog",
        "",
        "<!-- GENERATED by scripts/arsenal_audit.py from arsenal/registry.json. DO NOT EDIT BY HAND. -->",
        "",
        f"Schema version: `{data['schema_version']}`",
        "",
        "Lifecycle status is an evidence claim: `draft` and `unverified` do not imply poor quality; they mean the asset has not yet earned `testing` or `stable` under the registry contract.",
        "",
    ]

    for category in sorted(groups):
        lines += [f"## {category}", "", "| ID | Kind | Status | Purpose | Path |", "|---|---|---|---|---|"]
        for a in sorted(groups[category], key=lambda x: x["id"]):
            purpose = a["purpose"].replace("|", "\\|")
            lines.append(f"| `{a['id']}` | `{a['kind']}` | `{a['status']}` | {purpose} | `{a['path']}` |")
        lines.append("")

    source_count = sum(1 for a in data["assets"] if a["kind"] == "brief")
    lines += [
        "## Preserved source briefs",
        "",
        f"{source_count} source-generation artifacts are preserved under `briefs/` and registered as `kind: brief`. They are intentionally omitted from the primary capability tables.",
        "",
        "Use `arsenal/registry.json` for machine-readable relationships such as `upstream`, `downstream`, `source_brief`, and `source_for`.",
        "",
    ]
    return "\n".join(lines)


def audit(data):
    errors = []
    ids = {}
    paths = {}

    for i, asset in enumerate(data["assets"]):
        missing = REQUIRED - set(asset)
        if missing:
            errors.append(f"asset[{i}] missing fields: {sorted(missing)}")
            continue

        aid = asset["id"]
        path = asset["path"]

        if aid in ids:
            errors.append(f"duplicate id: {aid}")
        ids[aid] = asset

        if path in paths:
            errors.append(f"duplicate path: {path}")
        paths[path] = asset

        if asset["kind"] not in KINDS:
            errors.append(f"{aid}: invalid kind {asset['kind']!r}")
        if asset["status"] not in STATUSES:
            errors.append(f"{aid}: invalid status {asset['status']!r}")

        full = ROOT / path
        if not full.is_file():
            errors.append(f"{aid}: missing path {path}")
            continue

        text = full.read_text(encoding="utf-8", errors="replace")

        if asset["kind"] == "prompt":
            if "kind: prompt-generation-brief" in text:
                errors.append(f"{aid}: prompt contains prompt-generation-brief payload")
            if text.lstrip().startswith("# Master Sol/Fable Super-Prompt Generator"):
                errors.append(f"{aid}: prompt contains generator wrapper instead of canonical prompt")

        if asset["kind"] == "brief":
            if text.lstrip().startswith("# Master Sol/Fable Super-Prompt Generator"):
                errors.append(f"{aid}: brief duplicates canonical generator body")
            if "kind: prompt-generation-brief" not in text:
                errors.append(f"{aid}: brief is missing prompt-generation-brief marker")
            if f"generator: {CANONICAL_GENERATOR}" not in text:
                errors.append(f"{aid}: brief does not reference canonical generator")

    for asset in data["assets"]:
        aid = asset.get("id", "<unknown>")
        for field in ("upstream", "downstream"):
            for ref in asset.get(field, []):
                if ref not in ids:
                    errors.append(f"{aid}: unresolved {field} reference {ref}")

        source_brief = asset.get("source_brief")
        if source_brief:
            target = paths.get(source_brief)
            if not target:
                errors.append(f"{aid}: source_brief not registered: {source_brief}")
            elif target.get("kind") != "brief":
                errors.append(f"{aid}: source_brief is not kind=brief: {source_brief}")

        source_for = asset.get("source_for")
        if source_for and source_for not in ids:
            errors.append(f"{aid}: unresolved source_for reference {source_for}")

    expected = render_catalog(data)
    if not CATALOG.exists():
        errors.append("CATALOG.md is missing")
    elif CATALOG.read_text(encoding="utf-8") != expected:
        errors.append("CATALOG.md is stale; run scripts/arsenal_audit.py --write-catalog")

    return errors


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-catalog", action="store_true")
    args = parser.parse_args()

    try:
        data = load_registry()
    except Exception as exc:
        print(f"registry error: {exc}", file=sys.stderr)
        return 2

    if args.write_catalog:
        CATALOG.write_text(render_catalog(data), encoding="utf-8")
        print(f"wrote {CATALOG.relative_to(ROOT)}")

    errors = audit(data)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    print(f"arsenal integrity: PASS ({len(data['assets'])} registered assets)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
